my_website/config/routes.rb
MyWebsite::Application.routes.draw do
  root to: 'static_pages#home'

  resources :students do
    member do
      get 'student_info'
    end
  end

  match '/companies',   to: 'attending_companies#index'
  match '/students', to: 'students#index'

  resources :visiting_companies

  resources :attending_companies

  resources :students
  match 'students/:id'=> 'visiting_companies#new'

end

my_website/app/models/attending_company.rb
class AttendingCompany < ActiveRecord::Base
  attr_accessible :name, :day1, :day2, :specialization
  has_many :students
end

my_website/app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name, :specialization
 has_many :visiting_companies
end

my_website/app/models/visiting_company.rb
class VisitingCompany < ActiveRecord::Base
  attr_accessible  :student_id, :attending_company_id, :visited
  belongs_to :student
  end

my_website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

my_website/app/controllers/attending_companies_controller.rb
class AttendingCompaniesController < ApplicationController

  respond_to :html, :json, :xml

  def index
    @attending_companies = AttendingCompany.all
    respond_with @attending_companies
  end

  def show
    @attending_company = AttendingCompany.find(params[:id])
    respond_with @attending_company
  end

  def new
    @attending_company = AttendingCompany.new
    respond_with @attending_company
  end

  def edit
    @attending_company = AttendingCompany.find(params[:id])
  end

  def create
    @attending_company = AttendingCompany.new(params[:attending_company])

      if @attending_company.save
        respond_with @attending_company
        end

  end

  def update
    @attending_company = AttendingCompany.find(params[:id])

    respond_to do |format|
      if @attending_company.update_attributes(params[:attending_company])
        respond_with @attending_company
      else
        format.html { render action: "edit" }
        format.json { render json: @attending_company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @attending_company = AttendingCompany.find(params[:id])
    @attending_company.destroy
    respond_with @attending_company
  end
end

my_website/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

my_website/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  respond_to :html, :json, :xml

  def index
    @students = Student.all
    respond_with @students
  end

  def show
    @student = Student.find(params[:id])
    respond_with @student
  end

  def new
    @student = Student.new
    respond_with @student
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(params[:student])
    @student.save
    respond_to do |format|
      if @student.save
        respond_with @student
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def student_info
    @student = Student.find(params[:id])
    respond_to do | format |
      format.js {render :layout => false}
    end
  end

  def update
    @student = Student.find(params[:id])
    end


  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end
end

my_website/app/controllers/visiting_companies_controller.rb
class VisitingCompaniesController < ApplicationController

  respond_to :html, :json, :xml

  def index
    @visiting_companies = VisitingCompany.all
    respond_with @visiting_companies
  end

  def show
    @visiting_company = VisitingCompany.find(params[:id])
    respond_with @visiting_company
  end

  # GET /visiting_companies/new
  # GET /visiting_companies/new.json
  def new
    u = VisitingCompany.new
    u.student_id = params[:student_id]
    u.attending_company_id = params[:company_id]
    u.visited = false;
    u.save
     respond_to do |format|
      format.html{redirect_to Student.find(u.student_id)} # new.html.erb
     # format.json { render json: u }
    end
  end

  # GET /visiting_companies/1/edit
  def edit
    @visiting_company = VisitingCompany.find(params[:id])
  end

  def create
    @visiting_company = VisitingCompany.new(params[:visiting_company])

    respond_to do |format|
      if @visiting_company.save
        respond_with @visiting_company
      else
        format.html { render action: "new" }
        format.json { render json: @visiting_company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @visiting_company = VisitingCompany.find(params[:id])
    @visiting_company.visited = !@visiting_company.visited
    @visiting_company.save
    student_id = VisitingCompany.find(params[:id]).student_id
    respond_to do |format|
      format.html{redirect_to Student.find(student_id)}
    end

  end

  def destroy
    student_id = VisitingCompany.find(params[:id]).student_id
    @visiting_company = VisitingCompany.find(params[:id])
    @visiting_company.destroy

   respond_with @visiting_company
  end
end

my_website/app/helpers/application_helper.rb
module ApplicationHelper
end

my_website/app/helpers/attending_companies_helper.rb
module AttendingCompaniesHelper
end

my_website/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

my_website/app/helpers/students_helper.rb
module StudentsHelper
end

my_website/app/helpers/visiting_companies_helper.rb
module VisitingCompaniesHelper
end

my_website/app/views/attending_companies/_form.html.erb
<%= form_for(@attending_company) do |f| %>
  <% if @attending_company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attending_company.errors.count, "error") %> prohibited this attending_company from being saved:</h2>

      <ul>
      <% @attending_company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :day1 %><br />
    <%= f.check_box :day1 %>
  </div>
  <div class="field">
    <%= f.label :day2 %><br />
    <%= f.check_box :day2 %>
  </div>
  <div class="field">
    <%= f.label :specialization %><br />
    <%= f.text_field :specialization %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

my_website/app/views/attending_companies/edit.html.erb
<h1>Editing attending_company</h1>

<%= render 'form' %>

<%= link_to 'Show', @attending_company %> |
<%= link_to 'Back', attending_companies_path %>

my_website/app/views/attending_companies/index.html.erb
<h1>Attending Companies</h1>

<!-- Javascript goes in the document HEAD -->
<script type="text/javascript">
    function altRows(id){
        if(document.getElementsByTagName){

            var table = document.getElementById(id);
            var rows = table.getElementsByTagName("tr");

            for(i = 0; i < rows.length; i++){
                if(i % 2 == 0){
                    rows[i].className = "evenrowcolor";
                }else{
                    rows[i].className = "oddrowcolor";
                }
            }
        }
    }

    window.onload=function(){
        altRows('alternatecolor');
    }
</script>


<!-- CSS goes in the document HEAD or added to your external stylesheet -->
<style type="text/css">
    table.altrowstable {
        font-family: verdana,arial,sans-serif;
        font-size:11px;
        color:#333333;
        border-width: 1px;
        border-color: #a9c6c9;
        border-collapse: collapse;
    }
    table.altrowstable th {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #a9c6c9;
    }
    table.altrowstable td {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #a9c6c9;
    }
    .oddrowcolor{
        background-color:#d4e3e5;
    }
    .evenrowcolor{
        background-color:#c3dde0;
    }
</style>

 <td>
<!-- Table goes in the document BODY -->
<table class="altrowstable" id="alternatecolor">
  <tr>
    <th>Company name</th><th>Day 1</th><th>Day 2</th><th>Specialization</th>
  </tr>
    <% @attending_companies.each do |attending_company| %>
        <tr>
          <td><%= link_to attending_company.name , attending_company%></td>
          <td><%= attending_company.day1 %></td>
          <td><%= attending_company.day2 %></td>
          <td><%= attending_company.specialization %></td>
         </tr>
    <% end %>
  </table>
 </td>
<!--  The table code can be found here: http://www.textfixer/resources/css-tables.php#css-table03 -->


<!-- Table goes in the document BODY -->
<br />
 <td><%= button_to 'New Attending company',  new_attending_company_path, :method=> :get, class: "btn btn-large btn-primary" %></td>

my_website/app/views/attending_companies/new.html.erb
<h1>New attending_company</h1>

<%= render 'form' %>

<%= link_to 'Back', attending_companies_path %>

my_website/app/views/attending_companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @attending_company.name %>
</p>

<p>
  <b>Day1:</b>
  <%= @attending_company.day1 %>
</p>

<p>
  <b>Day2:</b>
  <%= @attending_company.day2 %>
</p>

<p>
  <b>Specialization:</b>
  <%= @attending_company.specialization %>
</p>


<%= link_to 'Edit', edit_attending_company_path(@attending_company) %> |
<%= link_to 'Back', attending_companies_path %>

my_website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "TOC Management System"  %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "TOC management system", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Attending Companies",   attending_companies_path %></li>
          <li><%= link_to "Students",    students_path%></li>
         </ul>
      </nav>
    </div>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

my_website/app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

my_website/app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>TOC management system</h1>

  <h2 background="background.jpg">
    This is the home page for the TOC manager developed by Venkatesh
  </h2>
  <div background="background.jpg"></div>
</div>



my_website/app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :specialization %><br />
    <%= f.text_field :specialization %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

my_website/app/views/students/_student.html.erb
<script type="text/javascript">
    function altRows(id){
        if(document.getElementsByTagName){

            var table = document.getElementById(id);
            var rows = table.getElementsByTagName("tr");

            for(i = 0; i < rows.length; i++){
                if(i % 2 == 0){
                    rows[i].className = "evenrowcolor";
                }else{
                    rows[i].className = "oddrowcolor";
                }
            }
        }
    }

    window.onload=function(){
        altRows('alternatecolor');
    }
</script>


<!-- CSS goes in the document HEAD or added to your external stylesheet -->
<style type="text/css">
    table.altrowstable {
        font-family: verdana,arial,sans-serif;
        font-size:11px;
        color:#333333;
        border-width: 1px;
        border-color: #a9c6c9;
        border-collapse: collapse;
    }
    table.altrowstable th {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #a9c6c9;
    }
    table.altrowstable td {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #a9c6c9;
    }
    .oddrowcolor{
        background-color:#d4e3e5;
    }
    .evenrowcolor{
        background-color:#c3dde0;
    }
</style>

<p>
  <b>Companies eligible for:</b>
<table>
  <td>
    <table class="altrowstable" id="alternatecolor">
      <tr>
        <th>Name</th>
        <th>Day1</th>
        <th>Day2</th>
      </tr>
      <% AttendingCompany.all.each do |attending_company| %>
          <% if (attending_company.specialization == @student.specialization) && (VisitingCompany.where( :student_id => @student.id , :attending_company_id=>attending_company.id ).length==0) %>
              <tr>
                <td><%= link_to attending_company.name,  attending_company %></td>
                <td><%= attending_company.day1 %></td>
                <td><%= attending_company.day2 %></td>
               </tr>
          <% end %>
      <% end %>
    </table>
  </td>

  <td>
    <table class="altrowstable"  >
      <tr>
        <th>Day 1 Companies not visited</th>
      </tr>
      <% VisitingCompany.all.each do |visiting_company| %>
          <% if (visiting_company.student_id == @student.id) && (visiting_company.visited==false)&& AttendingCompany.find(visiting_company.attending_company_id).day1 && (AttendingCompany.find(visiting_company.attending_company_id).specialization == @student.specialization ) %>
              <tr>
                <td><%= link_to AttendingCompany.find(visiting_company.attending_company_id).name, AttendingCompany.find(visiting_company.attending_company_id) %></td>

              </tr>
          <% end %>
      <% end %>
    </table>
          <br>
    <br>
    <table class="altrowstable" id="alternatecolor">
      <tr>
        <th>Day 1 Companies Visited</th>
      </tr>
      <% VisitingCompany.all.each do |visiting_company| %>
          <% if (visiting_company.student_id == @student.id) && (visiting_company.visited) && AttendingCompany.find(visiting_company.attending_company_id).day1 && (AttendingCompany.find(visiting_company.attending_company_id).specialization == @student.specialization ) %>
              <tr>
                <td><%= link_to AttendingCompany.find(visiting_company.attending_company_id).name, AttendingCompany.find(visiting_company.attending_company_id) %></td>

              </tr>
          <% end %>
      <% end %>
    </table>
  </td>
  <td>

    <table class="altrowstable" id="alternatecolor">
      <tr>
        <th>Day 2 Companies not visited</th>
      </tr>
      <% VisitingCompany.all.each do |visiting_company| %>
          <% if (visiting_company.student_id == @student.id) && (visiting_company.visited==false)&& AttendingCompany.find(visiting_company.attending_company_id).day2 && (AttendingCompany.find(visiting_company.attending_company_id).specialization == @student.specialization )  %>
              <tr>
                <td><%= link_to AttendingCompany.find(visiting_company.attending_company_id).name, AttendingCompany.find(visiting_company.attending_company_id) %></td>

              </tr>
          <% end %>
      <% end %>
    </table>

    <br>
    <br>

    <table class="altrowstable" id="alternatecolor">
      <tr>
        <th>Day 2 Companies Visited</th>
      </tr>
      <% VisitingCompany.all.each do |visiting_company| %>
          <% if (visiting_company.student_id == @student.id) && (visiting_company.visited) && AttendingCompany.find(visiting_company.attending_company_id).day2 && (AttendingCompany.find(visiting_company.attending_company_id).specialization == @student.specialization ) %>
              <tr>
                <td><%= link_to AttendingCompany.find(visiting_company.attending_company_id).name, AttendingCompany.find(visiting_company.attending_company_id) %></td>

              </tr>
          <% end %>
      <% end %>
    </table>
  </td>
</table>

</p>

my_website/app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

my_website/app/views/students/index.html.erb
<h1>Students</h1>
<h2>Click on "Check current TOC profile" to see the user's selected companies without going to their profile page</h2>

<!-- Javascript goes in the document HEAD -->
<script type="text/javascript">
    function altRows(id){
        if(document.getElementsByTagName){

            var table = document.getElementById(id);
            var rows = table.getElementsByTagName("tr");

            for(i = 0; i < rows.length; i++){
                if(i % 2 == 0){
                    rows[i].className = "evenrowcolor";
                }else{
                    rows[i].className = "oddrowcolor";
                }
            }
        }
    }

    window.onload=function(){
        altRows('alternatecolor');
    }
</script>


<!-- CSS goes in the document HEAD or added to your external stylesheet -->
<style type="text/css">
    table.altrowstable {
        font-family: verdana,arial,sans-serif;
        font-size:11px;
        color:#333333;
        border-width: 1px;
        border-color: #a9c6c9;
        border-collapse: collapse;
    }
    table.altrowstable th {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #a9c6c9;
    }
    table.altrowstable td {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #a9c6c9;
    }
    .oddrowcolor{
        background-color:#d4e3e5;
    }
    .evenrowcolor{
        background-color:#c3dde0;
    }
</style>
<table class="altrowstable" id="alternatecolor">
  <tr>
    <th>Name</th>
    <th>Specialization</th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.specialization %></td>
     <td><%= button_to 'Edit student info', edit_student_path(student), method: :get, class: "btn btn-small btn-primary" %></td>
     <td><%= button_to 'Check current TOC profile', student_info_student_path(:id => student.id), :method=> :get, :remote => true, class: "btn btn-small btn-primary" %></td>
    <td><%= button_to 'Go to TOC Profile',  student, :method => :get, class: "btn btn-small btn-primary" %>
    <td><%= link_to 'Remove Student', student,confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= button_to 'New Student', new_student_path,:method => :get, class: "btn btn-large btn-primary" %>

<div id="student_info"></div>

my_website/app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

my_website/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Specialization:</b>
  <%= @student.specialization %>
</p>

<script type="text/javascript">
    function altRows(id){
        if(document.getElementsByTagName){

            var table = document.getElementById(id);
            var rows = table.getElementsByTagName("tr");

            for(i = 0; i < rows.length; i++){
                if(i % 2 == 0){
                    rows[i].className = "evenrowcolor";
                }else{
                    rows[i].className = "oddrowcolor";
                }
            }
        }
    }

    window.onload=function(){
        altRows('alternatecolor');
    }
</script>


<!-- CSS goes in the document HEAD or added to your external stylesheet -->
<style type="text/css">
    table.altrowstable {
        font-family: verdana,arial,sans-serif;
        font-size:11px;
        color:#333333;
        border-width: 1px;
        border-color: #a9c6c9;
        border-collapse: collapse;
    }
    table.altrowstable th {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #a9c6c9;
    }
    table.altrowstable td {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #a9c6c9;
    }
    .oddrowcolor{
        background-color:#d4e3e5;
    }
    .evenrowcolor{
        background-color:#c3dde0;
    }
</style>

<p>
  <b>Companies eligible for:</b>
<table>
  <td>
    <table class="altrowstable">
      <tr>
        <th>Name</th>
        <th>Day1</th>
        <th>Day2</th>
      </tr>
      <% AttendingCompany.all.each do |attending_company| %>
          <% if (attending_company.specialization == @student.specialization) && (VisitingCompany.where( :student_id => @student.id , :attending_company_id=>attending_company.id ).length==0) %>
              <tr>
                <td><%= link_to attending_company.name,  attending_company %></td>
                <td><%= attending_company.day1 %></td>
                <td><%= attending_company.day2 %></td>
                <td><%= button_to("Add Visiting Company", {:method => 'new_visiting_company', :student_id => @student.id, :company_id => attending_company.id},class: "btn btn-small btn-primary")%></td>
              </tr>
          <% end %>
      <% end %>
    </table>
  </td>

  <td>
    <table class="altrowstable" id="alternatecolor1" >
      <tr>
        <th>Day 1 Companies not visited</th>
      </tr>
      <% VisitingCompany.all.each do |visiting_company| %>
          <% if (visiting_company.student_id == @student.id) && (visiting_company.visited==false)&& AttendingCompany.find(visiting_company.attending_company_id).day1 && (AttendingCompany.find(visiting_company.attending_company_id).specialization == @student.specialization ) %>
              <tr>
                <td><%= link_to AttendingCompany.find(visiting_company.attending_company_id).name, AttendingCompany.find(visiting_company.attending_company_id) %></td>
                <td><%= button_to("Remove", visiting_company_path(visiting_company.id) , {:method => :delete})%></td>
                <td><%= button_to("Add to visited", visiting_company_path(visiting_company.id) , {:method=> :put})%></td>
              </tr>
          <% end %>
      <% end %>
    </table>

    <br>
    <br>

    <table class="altrowstable" id="alternatecolor2">
      <tr>
        <th>Day 1 Companies Visited</th>
      </tr>
      <% VisitingCompany.all.each do |visiting_company| %>
          <% if (visiting_company.student_id == @student.id) && (visiting_company.visited) && AttendingCompany.find(visiting_company.attending_company_id).day1 && (AttendingCompany.find(visiting_company.attending_company_id).specialization == @student.specialization ) %>
              <tr>
                <td><%= link_to AttendingCompany.find(visiting_company.attending_company_id).name, AttendingCompany.find(visiting_company.attending_company_id) %></td>
                <td><%= button_to("Remove", visiting_company_path(visiting_company.id) , {:method => :delete})%></td>
                <td><%= button_to("Remove from visited", visiting_company_path(visiting_company.id) , {:method=> :put})%></td>
              </tr>
          <% end %>
      <% end %>
    </table>
  </td>
  <td>
    <table class="altrowstable" id="alternatecolor3">
      <tr>
        <th>Day 2 Companies not visited</th>
      </tr>
      <% VisitingCompany.all.each do |visiting_company| %>
          <% if (visiting_company.student_id == @student.id) && (visiting_company.visited==false)&& AttendingCompany.find(visiting_company.attending_company_id).day2 && (AttendingCompany.find(visiting_company.attending_company_id).specialization == @student.specialization )  %>
              <tr>
                <td><%= link_to AttendingCompany.find(visiting_company.attending_company_id).name, AttendingCompany.find(visiting_company.attending_company_id) %></td>
                <td><%= button_to("Remove", visiting_company_path(visiting_company.id) , {:method => :delete})%></td>
                <td><%= button_to("Add to visited", visiting_company_path(visiting_company.id) , {:method=> :put})%></td>
              </tr>
          <% end %>
      <% end %>
    </table>

    <br>
    <br>

    <table class="altrowstable" id="alternatecolor4">
      <tr>
        <th>Day 2 Companies Visited</th>
      </tr>
      <% VisitingCompany.all.each do |visiting_company| %>
          <% if (visiting_company.student_id == @student.id) && (visiting_company.visited) && AttendingCompany.find(visiting_company.attending_company_id).day2 && (AttendingCompany.find(visiting_company.attending_company_id).specialization == @student.specialization ) %>
              <tr>
                <td><%= link_to AttendingCompany.find(visiting_company.attending_company_id).name, AttendingCompany.find(visiting_company.attending_company_id) %></td>
                <td><%= button_to("Remove", visiting_company_path(visiting_company.id) , {:method => :delete})%></td>
                <td><%= button_to("Remove from visited", visiting_company_path(visiting_company.id) , {:method=> :put})%></td>
              </tr>
          <% end %>
      <% end %>
    </table>
  </td>
</table>

</p>


<%= button_to 'Edit student information', edit_student_path(@student), :method=> :get, class: "btn btn-large btn-primary" %>
<%= button_to 'Back to students page', students_path, :method=> :get, class: "btn btn-large btn-primary" %>

my_website/app/views/students/student_info.js.erb
$( "#student_info" ).html( "<%= escape_javascript( render( :partial => "student", :locals => { :student => @student} ) ) %>" );

my_website/app/views/visiting_companies/_form.html.erb
<%= form_for(@visiting_company) do |f| %>
  <% if @visiting_company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visiting_company.errors.count, "error") %> prohibited this visiting_company from being saved:</h2>

      <ul>
      <% @visiting_company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :attending_company_id %><br />
    <%= f.number_field :attending_company_id %>
  </div>
  <div class="field">
    <%= f.label :visited %><br />
    <%= f.check_box :visited %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

my_website/app/views/visiting_companies/edit.html.erb
<h1>Editing visiting_company</h1>

<%= render 'form' %>

<%= link_to 'Show', @visiting_company %> |
<%= link_to 'Back', visiting_companies_path %>

my_website/app/views/visiting_companies/index.html.erb
<h1>Listing visiting_companies</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Student ID</th>
    <th>Student</th>
    <th>Attending company ID</th>
    <th>Attending company</th>
    <th>Visited</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visiting_companies.each do |visiting_company| %>
  <tr>
    <td><%= visiting_company.id %></td>
    <td><%= visiting_company.student_id %></td>
    <td><%= Student.find(visiting_company.student_id).name %></td>
    <td><%= visiting_company.attending_company_id %></td>
    <td><%= AttendingCompany.find(visiting_company.attending_company_id).name %></td>
    <td><%= visiting_company.visited %></td>
    <td><%= link_to 'Show', visiting_company %></td>
    <td><%= link_to 'Edit', edit_visiting_company_path(visiting_company) %></td>
    <td><%= link_to 'Destroy', visiting_company, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visiting company', new_visiting_company_path %>

my_website/app/views/visiting_companies/new.html.erb
<%= 'Successfully added the company'%>

my_website/app/views/visiting_companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= 'Successfully added ' + AttendingCompany.find(@visiting_company.attending_company_id).name + 'to student ' + Student.find(@visiting_company.student_id).name %>
</p>

<p>
  <b>Attending company:</b>
  <%= @visiting_company.attending_company_id %>
</p>

<p>
  <b>Visited:</b>
  <%= @visiting_company.visited %>
</p>


<%= link_to 'Edit', edit_visiting_company_path(@visiting_company) %> |
<%= link_to 'Back', visiting_companies_path %>